apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-job
spec:
  template:
    spec:
      containers:
      - name: wrk
        image: williamyeh/wrk
        args:
        - "-c5"
        - "-t5"
        - "-d300s"
        - "-H"
        - "Connection: Close"
        - "http://flask-app-service:5053/viewContacts"
      restartPolicy: Never