# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # set timeout to 600 seconds
  config.vm.boot_timeout = 600
 
  # config.vm.define "jenkins" do |jenkins|
  #   jenkins.vm.box = "bento/ubuntu-24.04"
  #   jenkins.vm.hostname = "jenkins"
  #   jenkins.vm.network "private_network", ip: "192.168.43.30"
  #   jenkins.vm.provider "virtualbox" do |vb|
  #     vb.name = "jenkins"
  #     vb.memory = "2048"
  #     vb.cpus = 2
  #   end
  #   # script to install jenkins + git and java
  #   jenkins.vm.provision "shell", path: "provisions/install-jenkins.sh"

   
  # end

  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "bento/ubuntu-24.04"
    agent1.vm.hostname = "agent1"
    agent1.vm.network "private_network", ip: "192.168.33.40"
    agent1.vm.provider "virtualbox" do |vb|
      vb.name = "agent1"
    end
    # script to install jenkins agent
    agent1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y openjdk-17-jdk git
    SHELL

  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "bento/ubuntu-24.04"
    agent2.vm.hostname = "agent2"
    agent2.vm.network "private_network", ip: "192.168.33.50"
    agent2.vm.provider "virtualbox" do |vb|
      vb.name = "agent2"
    end

    agent2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y openjdk-17-jdk git
    SHELL

  end



end
