apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-mongo
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template: #pod defintion
    metadata:
      labels:
        app: flask-app
    spec: # container specs
      containers:
        - name: flask-app
          image: shashkist/flask-contacts-app
          ports:
            - containerPort: 5052
          env:
          - name: DATABASE_TYPE
            value: "MONGO"
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"
       

---
apiVersion: v1
kind: Service
metadata:
 name: flask-app-service
 labels:
   app: flask-contacts-service # we will refernce here from service monitor
spec:
 selector:
   app: flask-app
 type: LoadBalancer # external service which can be accessed from outside the cluster
 ports:
   - name: flask-contacts-service # we will refernce here from service monitor
     protocol: TCP
     port: 5053
     targetPort: 5052   